name: dotnet-workflow

on:
  push:
    branches: none # [ main ]
  pull_request:
    branches: none # [ main ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  Dotnet-Sample-SonarCloudCodeReviewScan-Build-and-Test:
    name: Servion DevOps Sampele DotNet App
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: dotnet-sample-app
        
    steps:
      - name: Code Check out
        uses: actions/checkout@v4
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
  
      - name: Restore dependencies
        run: dotnet restore
      
      - name: Build
        run: dotnet build --no-restore
      
      - name: Test
        run: dotnet test --no-build --verbosity normal

      - name: Code Scan with Sonar Cloud
        with:
          fetch-depth: 0
        uses: sonarsource/sonarcloud-github-action@Latest
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
          SONAR_TOKEN: ${{ secrets. SONAR_TOKEN }}
