name: dotnet-workflow

on:
  push:
    branches: none # [ main ]
  pull_request:
    branches: none # [ main ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  SonarCloudCodeReviewScan:
    name: SonarCloud Scan
    runs-on: ubuntu-latest
    steps:
      - name: clone Repo for Code Scan
      uses: actions/checkout@v4
      -name: Code Scan with Sonar Cloud
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
        SONAR_TOKEN: ${{ secrets. SONAR TOKEN }}
jobs:
  build-dotnet-app:

    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: dotnet-sample-app

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
  
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
